# Use Java 8 slim JRE
FROM alpine:latest

# JMeter version
ARG JMETER_VERSION=3.3

# Install few utilities
RUN apk update && \
    apk add ca-certificates && \
    update-ca-certificates && \
    apk add \
        wget \
        telnet \
        iputils-ping \
        unzip

# Install JMeter
WORKDIR /jmeter
RUN wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz \
    && tar -xzf apache-jmeter-$JMETER_VERSION.tgz \
    && rm apache-jmeter-$JMETER_VERSION.tgz



# COPY the server file to image from builder
FROM openjdk:8-jre-alpine

RUN apk update && \
    apk add ca-certificates && \
    rm -rf /var/cache/apk/*

WORKDIR /jmeter
COPY --from=builder /jmeter/apache-jmeter-$JMETER_VERSION /jmeter/

# Set JMeter Home
ENV JMETER_HOME /jmeter

# Add JMeter to the Path
ENV PATH $JMETER_HOME/bin:$PATH

EXPOSE 1099 50000

ENTRYPOINT jmeter-server \
-Dserver.rmi.localport=50000 \
-Dserver_port=1099