apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jmeter-slaves-dep
  namespace: jmslave
  labels:
    jmeter_mode: slave
spec:
  selector:
    matchLabels:
      jmeter_mode: slave
  replicas: 2
  template:
    metadata:
      namespace: jmslave
      labels:
        jmeter_mode: slave
    spec:
      containers:
        - name: jmslave
          image: gcr.io/develop-220914/jmeter:slave
          ports:
            - containerPort: 1099
            - containerPort: 50000
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-slaves-svc
  namespace: jmslave
  labels:
    jmeter_mode: slave
spec:
  type: LoadBalancer
  ports:
    - port: 1099
      name: server
      protocol: TCP
      targetPort: 1099
    - port: 50000
      name: local
      protocol: TCP
      targetPort: 50000
  selector:
    jmeter_mode: slave