apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jmeter-slaves-dep
  namespace: jmslave
  labels:
    jmeter_mode: slave
spec:
  selector:
    matchLabels:
      jmeter_mode: slave
  replicas: 3
  template:
    metadata:
      namespace: jmslave
      labels:
        jmeter_mode: slave
    spec:
      containers:
        - name: jmslave
          image: gcr.io/develop-220914/jmeter:slave
          ports:
            - containerPort: 1099
            - containerPort: 50000