apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jmeter-slaves-dep
  namespace: jmslave
  labels:
    jmeter_mode: slave
spec:
  selector:
    matchLabels:
      jmeter_mode: slave
  # replicas: 2
  template:
    metadata:
      namespace: jmslave
      labels:
        jmeter_mode: slave
    spec:
      containers:
        - name: jmslave
          image: lisdar/jmeter-kubernetes:slave
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1099
            - containerPort: 50000
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-slaves-svc
  namespace: jmslave
  labels:
    jmeter_mode: slave
spec:
  clusterIP: None
  ports:
    - port: 1099
      name: first
      targetPort: 1099
    - port: 50000
      name: second
      targetPort: 50000
  selector:
    jmeter_mode: slave